server:
  port: 8080

spring:
  application:
    name: bff
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: web-bff
            client-secret: ${BFF_CLIENT_SECRET:HArVdTFomBBbHQMdSDOeVyFF2m86ytVJ}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/opes}

logging:
  level:
    org.springframework.security: INFO
