server:
  port: 8080
  forward-headers-strategy: framework   # utile quando metterai Nginx davanti

spring:
  application:
    name: bff
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: web-bff
            client-secret: ${BFF_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${PROVIDER_KEYCLOAK_URI}

server.servlet.session:
  timeout: 30m
  cookie:
    name: BFFSESSION
    http-only: true
    # in localhost restiamo su HTTP; quando andrai su https puoi settare:
    # secure: true
    # same-site: lax  # se frontend e BFF stesso host; "none" solo se domini diversi e https

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.springframework.security: INFO
